_target_: src.model.vae.VAE
image_size: ${dataset.size}
in_channels: 3
hidden_dims: [8, 16, 32]
latent_dim: 20
activation: relu
norm_type: batchnorm
use_res: false
use_attn: false
attn_res_enc: null
attn_res_dec: null
upsample_mode: nearest
output_range: sigmoid
init_mode: normal
